Repository sinProject-Inc/sinpro-dev, pull requests merged in 2023-09, with the labels that each got.

#265 Add Chrome Extension #257
  docs/20-dev-environment/15-chrome-extensions.md
Labels: enhancement

#271 Use gpt4 for code review by akiojin #269
  .github/workflows/cr-akiojin-gpt-4.yml
  .vscode/settings.json
  docs/50-git/50-github-actions.md
Labels: documentation, enhancement

#272 Update PR Template #268
  .github/pull_request_template.md
Labels: enhancement

#274 Update PR template #273
  .github/pull_request_template.md
Labels: enhancement

#276 Update .eslintrc.cjs #275
  .eslintrc.cjs
  docs/35-code-style/30-eslint.md
  src/lib/background/background.ts
  src/lib/docs/markdown.ts
  src/lib/docs/markdown_code_element.ts
  src/lib/docs/search_result_context.ts
  src/lib/git/create_git_branch.ts
  src/routes/docs/+layout.svelte
Labels: breaking-change

#283 Update npm packages #281
  package-lock.json
  package.json
  src/lib/assets/search_index.json
Labels: enhancement

#282 Add Events Page #280
  docs/10-company-information/40-events.md
  static/unveiling-innovations.avif
Labels: enhancement

#285 Verify if the newly created files have been checked #284
  .github/workflows/cr-akiojin-gpt-4.yml
Labels: enhancement

#290 Update PR template #289
  .github/pull_request_template.md
Labels: enhancement

#292 Refactoring test codes using GPT-4 #291
  docs/20-dev-environment/80-chatgpt-prompts.md
  src/lib/app/app.test.ts
  src/lib/app/app.ts
  src/lib/app/logger.test.ts
  src/lib/docs/current_page_store.test.ts
  src/lib/docs/markdown.test.ts
  src/lib/docs/markdown_code_element.test.ts
  src/lib/general/formatted_date.test.ts
  src/lib/general/formatted_date.ts
  src/lib/general/sentence_service.test.ts
  src/lib/general/system.test.ts
  src/lib/network/client_address.test.ts
Labels: enhancement

#297 Add Merge pull request section to GitHub Pull Request Page #296
  docs/50-git/40-github-pull-requests.md
Labels: enhancement

#300 Update Issue Template #298
  .github/ISSUE_TEMPLATE/custom.md
Labels: enhancement

#301 Update PR Template #299
  .github/pull_request_template.md
Labels: enhancement

#306 Update git settings #304
  docs/50-git/10-git-branches-and-commits.md
  docs/50-git/20-git-hooks.md
  docs/50-git/30-git-user-profiles.md
  docs/50-git/40-git-for-windows.md
  docs/51-github/10-github-issues.md
  docs/51-github/20-github-pull-requests.md
  docs/51-github/30-github_repository_settings.md
  docs/51-github/40-github-branch-protection.md
  docs/51-github/50-github-actions.md
  docs/51-github/meta.json
Labels: enhancement

#308 Add a test.each sample to the Vitest page #307
  docs/40-testing/10-vitest.md
Labels: enhancement

#315 Update the test code referring to the latest skelton of SvelteKit #314
  .github/actions/setup-and-cache/action.yml
  .github/workflows/ci.yml
  .husky/pre-push
  docs/40-testing/20-playwright.md
  docs/50-git/20-git-hooks.md
  docs/51-github/50-github-actions.md
  package.json
Labels: breaking-change

#317 Change lint scripts #316
  package.json
Labels: enhancement

#319 Prevent commits directory to main branch #318
  .husky/pre-commit
  docs/50-git/20-git-hooks.md
Labels: enhancement

#321 Set tsconfig to strictest #320
  src/lib/background/background.ts
  src/lib/docs/markdown.ts
  src/lib/docs/search_index.ts
  src/lib/docs/search_result_context.ts
  src/lib/network/client_address.test.ts
  src/lib/network/client_hostname.ts
  src/routes/+layout.svelte
  src/routes/docs/+layout.svelte
  src/routes/docs/[slug]/ad_sense.svelte
  src/routes/docs/search_modale.svelte
  src/scripts/create_git_branch.ts
  tsconfig.json
Labels: breaking-change

#323 Configure Playwright #322
  docs/40-testing/20-playwright.md
  playwright.config.ts
  tests/docs.spec.ts
Labels: breaking-change
