Repository sinProject-Inc/sinpro-dev, pull requests merged in 2023-07, with the labels that each got.

#27 Update issue template #12
  .github/ISSUE_TEMPLATE/custom.md
  .github/pull_request_template.md
Labels: enhancement

#32 Add static header to Caddyfile #30
  .server/etc/caddy/Caddyfile
  docs/60-server/30-caddy.md
  nginx/nginx.conf
Labels: enhancement

#33 Change the tab size of the code block #31
  src/lib/app.css
Labels: enhancement

#34 Change the menu #17
  src/lib/components/github_link.svelte
  src/lib/components/icons/twitter_icon.svelte
  src/lib/components/menu_items_sub.svelte
  src/lib/components/nav_item.svelte
  src/lib/components/nav_item_tab.svelte
  src/lib/components/navbar.svelte
  src/lib/components/twitter_link.svelte
Labels: maintenance

#45 Add the services page #43
  docs/10-company-information/20-about.md
  docs/10-company-information/30-services.md
  static/office.avif
Labels: enhancement

#48 Add: Using ESLint with Svelte #44
  docs/35-code-style/30-eslint.md
Labels: enhancement

#50 Add the tabsize rule #49
  .eslintrc.cjs
  .vscode/settings.json
  docs/20-dev-environment/20-vscode-workspace-settings.md
  docs/35-code-style/30-eslint.md
  e2e/docs.spec.ts
Labels: enhancement

#51 Add file name rules #20
  docs/30-clean-code/15-format.md
Labels: enhancement

#53 Fix English #52
  docs/10-company-information/10-portfolio.md
  docs/10-company-information/30-services.md
Labels: documentation

#61 Prefix private members with an underscore #60
  docs/30-clean-code/40-objects-and-data-structures.md
Labels: enhancement

#63 Prefer const #62
  docs/30-clean-code/20-variables.md
Labels: enhancement

#65 Add Chrome Extensions #64
  docs/20-dev-environment/15-chrome-extensions.md
Labels: enhancement

#67 Add: Video Speed Controller to Chrome Extensions #66
  docs/20-dev-environment/15-chrome-extensions.md
Labels: enhancement

#71 Fix dead links #69
  docs/40-testing/10-vitest.md
  docs/40-testing/20-playwright.md
Labels: maintenance

#75 Add releases to history #73
  docs/70-team-sinproject/99-docs-history.md
Labels: enhancement

#77 Adjust docs side bar #76
  src/routes/docs/mobile_docs_side_bar.svelte
Labels: enhancement

#84 Add Install Tailwind CSS with SvelteKit #83
  docs/20-dev-environment/90-tailwind-css.md
Labels: enhancement

#116 Write issue titles in affirmative form #91
  docs/50-git/30-github-issues.md
Labels: enhancement

#130 Update to Prettier 3 #129
  .prettierrc
  package-lock.json
  package.json
  src/app.html
  src/lib/app.css
Labels: enhancement

#136 Implement AdSense #135
  static/abs.txt
Labels: enhancement
